#!/usr/bin/env bash
# Compatibility smoke gate (issue #679).
#
# Boots the operator from the COMMITTED image digest in
# deploy/operator-deployment.yaml (never overridden) against the CURRENT
# deploy/ manifest set on a disposable single-node kind cluster, and
# asserts the pair is mutually compatible. This is the exact snapshot a
# cluster admin gets from `kubectl apply -f deploy/` — release.yml re-pins
# the digest on every develop push, but nothing else guarantees the
# committed pin has not drifted behind RBAC/VAP/CRD semantics that moved
# ahead of the last published dev image.
#
# Regression assertions (the two live-observed failure signatures from
# the issue, plus a liveness signal):
#
#   (a) NO `empty spec.redisUrl` warning in operator logs — the #116
#       fence must stay silent when spec.redisCredentials.secretRef
#       resolves (the pre-#463 pinned digest cannot resolve secretRefs
#       at all and warns even though the CR carries one).
#   (b) NO main-resource PATCH 403 / Forbidden in operator logs — the
#       #228 RBAC deliberately grants patch/update ONLY on the /status
#       subresource; a kopf that PATCHes the read-only main OSCM
#       resource (pre-#681 bookkeeping) retry-storms APIForbiddenError.
#   (c) The operator pod reaches Ready (readiness probe on the :9090
#       metrics endpoint) AND the OSCM timers tick (any
#       `tick skipped, retrying next poll` / idle-tick log evidence —
#       assertions are log/behavior-shaped, NOT entrypoint-shaped, so
#       an old pinned digest using the `kopf run` CLI still passes when
#       it is otherwise compatible).
#
# Scope: OPERATOR-vs-MANIFEST compatibility only, not full stack health.
# The OpenStudio web/Redis Services named by the fixture CR do NOT exist
# in this cluster — REST/Redis connectivity failures are expected and
# fine; the assertions are about the SECRET-RESOLUTION path and the
# RBAC-vs-patch contract. The pruner CronJob, KEDA, quotas, and the
# observability manifests are out of scope here.
#
# Environment knobs:
#   KIND_CLUSTER_NAME            cluster name (default: oscm-compat-smoke)
#   COMPAT_SMOKE_WAIT_SECONDS    pod-Ready timeout (default: 120)
#   COMPAT_SMOKE_SETTLE_SECONDS  post-Ready log window (default: 60 —
#                                covers >=1 SLA-timer fire at its 30s
#                                cadence even with a slow first fire)
#   COMPAT_SMOKE_KEEP_CLUSTER    1 = keep the cluster on exit (debug)
#
# Requires on PATH: docker, kind, kubectl. Kind's bundled default node
# image (same posture as scripts/create-kind-cluster.sh, which pins no
# node image) is Kubernetes 1.30+, so the VAP manifests apply; on a
# pre-1.30 kind the VAP applies are tolerated as best-effort warnings.
#
# Exit: 0 = compatible; 1 = any assertion failed (summary printed).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd -P)"

CLUSTER_NAME="${KIND_CLUSTER_NAME:-oscm-compat-smoke}"
NAMESPACE="openstudio-server"
WAIT_SECONDS="${COMPAT_SMOKE_WAIT_SECONDS:-120}"
SETTLE_SECONDS="${COMPAT_SMOKE_SETTLE_SECONDS:-60}"
KEEP_CLUSTER="${COMPAT_SMOKE_KEEP_CLUSTER:-0}"

# Not a real credential anywhere — lives only inside the disposable
# kind cluster's Secret object for the duration of the gate run.
REDIS_URL_VALUE="redis://:compat-smoke-rotated@queue.openstudio-server.svc.cluster.local:6379"

FAILURES=0
KIND_CONFIG="$(mktemp)"
LOG_FILE="$(mktemp)"

for tool in docker kind kubectl; do
    if ! command -v "$tool" >/dev/null 2>&1; then
        echo "ERROR: required tool '$tool' not found on PATH." >&2
        exit 1
    fi
done

if ! docker info >/dev/null 2>&1; then
    echo "ERROR: docker daemon is not reachable (docker info failed)." >&2
    exit 1
fi

teardown() {
    rm -f "${KIND_CONFIG:-}" "${LOG_FILE:-}"
    if [ "${KEEP_CLUSTER:-0}" = "1" ]; then
        echo "KEEP_CLUSTER=1 — leaving kind cluster '$CLUSTER_NAME' running."
        return
    fi
    echo "Tearing down kind cluster '$CLUSTER_NAME' ..."
    kind delete cluster --name "$CLUSTER_NAME" >/dev/null 2>&1 || true
}
trap teardown EXIT

# --- 1. disposable kind cluster (repo recipe: single control-plane node,
#        default node image, kubelet pulls the pinned image itself) ------
if kind get clusters 2>/dev/null | grep -qx "$CLUSTER_NAME"; then
    echo "Deleting stale kind cluster '$CLUSTER_NAME' first ..."
    kind delete cluster --name "$CLUSTER_NAME"
fi
cat >"$KIND_CONFIG" <<EOF
# Generated by scripts/compat-smoke-gate.sh (issue #679) — mirrors
# scripts/kind-config.yaml but under the gate's disposable cluster name.
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ${CLUSTER_NAME}
nodes:
  - role: control-plane
EOF
echo "Creating kind cluster '$CLUSTER_NAME' ..."
kind create cluster --name "$CLUSTER_NAME" --config "$KIND_CONFIG"
kubectl wait --for=condition=Ready node --all --timeout=300s

# --- 2. apply the CURRENT deploy/ set ----------------------------------
echo "Applying the current deploy/ set ..."
kubectl apply -f "$REPO_ROOT/deploy/namespace-labels.yaml"
# PriorityClass must exist before the Deployment — admission rejects
# pods naming a nonexistent priorityClassName.
kubectl apply -f "$REPO_ROOT/deploy/priority-class.yaml"
kubectl apply -f "$REPO_ROOT/deploy/crd.yaml"
kubectl wait --for=condition=Established crd/openstudioclustermanagers.energy.nrel.gov --timeout=120s
kubectl apply -f "$REPO_ROOT/deploy/rbac.yaml"
# Credential secrets: sentinel placeholders are fine for boot — the
# operator's only Secret read is the #463 bounded exception below.
kubectl apply -f "$REPO_ROOT/deploy/redis-credentials-secret.yaml"
kubectl apply -f "$REPO_ROOT/deploy/mongo-credentials-secret.yaml"
# Give the canonical Secret the #463 full-URL key the fixture CR names —
# unreachable Redis is fine; the assertion is that the operator RESOLVES
# the ref (and so stays silent on the #116 fence).
kubectl -n "$NAMESPACE" patch secret openstudio-redis --type merge \
    -p "{\"stringData\":{\"redis-url\":\"${REDIS_URL_VALUE}\"}}"

# VAP companions (#293/#572/#573): best-effort — they narrow the operator
# SA further than RBAC, but the gate's contract assertions are
# RBAC-shaped. Tolerate a pre-1.30 API server (admissionregistration
# v1 GA gate) with a warning instead of failing the run.
for vap in pod-delete-admission-policy.yaml secret-read-admission-policy.yaml \
           deployment-patch-admission-policy.yaml; do
    if ! kubectl apply -f "$REPO_ROOT/deploy/$vap" >/dev/null 2>&1; then
        echo "WARN: could not apply deploy/$vap (pre-1.30 kind node?) — continuing RBAC-only."
    fi
done

# NetworkPolicies (egress fence + metrics ingress) select the operator
# pod by label; kind's CNI enforces them where supported. The apiserver
# egress peer (#578) keeps the operator's own API traffic flowing.
kubectl apply -f "$REPO_ROOT/deploy/network-policy.yaml"

# The operator Deployment — AS COMMITTED. The pinned digest is the
# thing under test; never override the image here.
kubectl apply -f "$REPO_ROOT/deploy/operator-deployment.yaml"

# --- 3. fixture OSCM CR (#463 secretRef shape) --------------------------
echo "Creating the compat-smoke OSCM CR (secretRef shape, dryRun) ..."
cat <<'EOF' | kubectl apply -f -
apiVersion: energy.nrel.gov/v1alpha1
kind: OpenStudioClusterManager
metadata:
  name: compat-smoke
  namespace: openstudio-server
spec:
  # In-cluster Service URL per the #160/#575 CRD pattern; the Service
  # does not exist in this cluster — REST unreachability is expected and
  # irrelevant to the assertions.
  serverUrl: http://web.openstudio-server.svc.cluster.local:80
  redisCredentials:
    secretRef:
      name: openstudio-redis
      key: redis-url
  # Belt-and-braces: even a compatibility-broken digest must not mutate
  # anything while we watch it.
  dryRun: true
EOF

# --- 4. wait for Ready, then observe the log window ---------------------
echo "Waiting up to ${WAIT_SECONDS}s for the operator pod to report Ready ..."
if kubectl -n "$NAMESPACE" wait --for=condition=Ready pod \
        -l app=openstudio-operator --timeout="${WAIT_SECONDS}s"; then
    READY_OK=1
else
    READY_OK=0
    echo "FAIL: operator pod did not reach Ready within ${WAIT_SECONDS}s."
    echo "      (The current Deployment's probes require the :9090 /metrics"
    echo "       endpoint — a pinned digest that predates it is precisely"
    echo "       the deploy/-vs-digest skew this gate exists to catch.)"
    kubectl -n "$NAMESPACE" get pods -l app=openstudio-operator || true
fi

echo "Settling ${SETTLE_SECONDS}s to observe timer logs ..."
sleep "$SETTLE_SECONDS"

LOG_LINES=0
if kubectl -n "$NAMESPACE" logs deployment/openstudio-operator \
        --all-containers=true >"$LOG_FILE" 2>&1; then
    LOG_LINES=$(wc -l <"$LOG_FILE")
else
    echo "WARN: could not collect operator logs; continuing with what we have."
fi

if [ "$LOG_LINES" -eq 0 ]; then
    echo "FAIL: no operator logs collected — the pinned digest never ran far"
    echo "      enough to log (image pull failure or crash-loop?). Pod state:"
    kubectl -n "$NAMESPACE" describe pod -l app=openstudio-operator | tail -n 30 || true
    echo "=== compat-smoke-gate: FAIL (no log evidence) ==="
    exit 1
fi

# --- 5. assertions ------------------------------------------------------
echo
echo "=== compat-smoke assertions ==="

# (a) #116 fence must stay silent when secretRef resolves (#463).
if grep -q "empty spec.redisUrl" "$LOG_FILE"; then
    echo "FAIL (a): 'empty spec.redisUrl' warning present — the pinned digest"
    echo "      cannot resolve spec.redisCredentials.secretRef (#116/#463 skew)."
    grep -m 3 "empty spec.redisUrl" "$LOG_FILE" || true
    FAILURES=$((FAILURES + 1))
else
    echo "PASS (a): no 'empty spec.redisUrl' warning (secretRef resolution path OK)."
fi

# (b) No main-resource PATCH 403 / Forbidden (#228 shape).
if grep -Eq "403|[Ff]orbidden" "$LOG_FILE"; then
    echo "FAIL (b): 403/Forbidden present in operator logs — the pinned digest"
    echo "      PATCHes a surface current deploy/rbac.yaml does not grant (#228 shape,"
    echo "      e.g. kopf bookkeeping on the read-only main OSCM resource)."
    grep -m 5 -E "403|[Ff]orbidden" "$LOG_FILE" || true
    FAILURES=$((FAILURES + 1))
else
    echo "PASS (b): no 403/Forbidden in operator logs (RBAC contract holds)."
fi

# (c) Ready + timers ticking (log-shaped, not entrypoint-shaped).
TICK_EVIDENCE=$(grep -Ec "tick skipped, retrying next poll|idle this tick" "$LOG_FILE" || true)
if [ "$READY_OK" = "1" ] && [ "${TICK_EVIDENCE:-0}" -gt 0 ]; then
    echo "PASS (c): pod Ready + ${TICK_EVIDENCE} timer tick log line(s)."
else
    echo "FAIL (c): pod Ready=${READY_OK}, timer tick log lines=${TICK_EVIDENCE:-0}."
    echo "      Last 40 operator log lines for triage:"
    tail -n 40 "$LOG_FILE" || true
    FAILURES=$((FAILURES + 1))
fi

# --- 6. summary ----------------------------------------------------------
echo
if [ "$FAILURES" -gt 0 ]; then
    echo "=== compat-smoke-gate: FAIL ($FAILURES assertion(s)) ==="
    echo "The committed image digest in deploy/operator-deployment.yaml is NOT"
    echo "compatible with the current deploy/ manifests. If this run follows"
    echo "RBAC/VAP/CRD semantic changes, repin the digest (release.yml does it"
    echo "on every develop push) or make the manifests and image agree — see"
    echo "docs/validation.md Prerequisites (issue #679)."
    exit 1
fi
echo "=== compat-smoke-gate: PASS — committed digest + current deploy/ are mutually compatible ==="
